name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        name: Install Current .NET SDK
      - name: Restore dependencies
        run: dotnet restore /p:TreatWarningsAsErrors=true
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=true

  nupkg:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        name: Install Current .NET SDK
      - name: Generate NuGet Packages
        run: dotnet pack --configuration Release --output nupkg /p:TreatWarningsAsErrors=true
      - uses: actions/upload-artifact@v4
        if: success() && github.ref == 'refs/heads/main'
        with:
          name: nupkg
          path: nupkg/*
          retention-days: 1
